import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      // Header
      "home": "Home",
      "sale": "Sale",
      "rent": "Rent",
      "news": "News",
      "contact": "Contact Us",
      "signup": "Sign Up",
      "login": "Login",
      // Login & SignUp Page
      "username": "Username",
      "password": "Password",
      "email": "Email",
      "confirm_password": "Confirm Password",
      "create_account": "Create New Account",
      "login_now": "Login Now",
      "forgot_password": "Forgot Password?",
      "have_account": "Already have an account?",
      "no_account": "Don't have an account?",
      "welcome_title": "Find Your Dream Home",
      "hero_title": "Find Your Dream Home",
      "hero_subtitle": "We provide the best real estate buy, sell, and rent services in Cambodia",
      "search_placeholder": "Search location or property type...",
      "all_types": "All Types",
      "search_btn": "Search",
      "our_services": "Our Main Services",
      "featured_projects": "Latest Projects",
      "curated_for_you": "Carefully selected for you",
      "view_all": "View All",
      "special_offer": "Special Offer",
      "new_listing": "New Listing",
      "hot_deal": "Hot Deal",
      "villa_title": "Modern Twin Villa Chroy Changvar",
      "shophouse_title": "Shophouse near Mall",
      "condo_title": "Modern Condo City Center",
      "phnom_penh": "Phnom Penh",
      "bed_count": "{{count}} Bedrooms",
      "bath_count": "{{count}} Bathrooms",
      "cta_title": "Want to sell or rent your property?",
      "cta_subtitle": "Our expert agents will help you get the best price quickly.",
      "consult_now": "Consult Now",
      "default_service_desc": "Explore many great options available.",
      "footer_about": "We are a leading real estate agency in Cambodia, providing buying, selling, and renting services with the highest trust and transparency for our customers.",
      "quick_links": "Quick Links",
      "our_services_footer": "Our Services",
      "service_1": "Property Valuation",
      "service_2": "Investment Consulting",
      "service_3": "Ownership Transfer Service",
      "service_4": "Rental Property Management",
      "contact_us_footer": "Contact Us",
      "address": "Boeung Keng Kang 1, Phnom Penh",
      "copyright": "© 2026 Managed by Mr. Meng Hor. All Rights Reserved.",
      "properties_for_sale": "Properties For Sale",
      "showing_results": "Showing results: {{count}} locations",
      "all_locations": "All Locations",
      "kandal": "Kandal",
      "siem_reap": "Siem Reap",
      "property_type": "Property Type",
      "villa": "Villa",
      "flat": "FlatHouse/Apartment",
      "land_lot": "Land Lot",
      "price_range": "Price Range",
      "under_50k": "Under $50,000",
      "50k_100k": "$50,000 - $100,000",
      "over_100k": "Over $100,000",
      "hard_title": "Hard Title",
      "urgent_sale": "Urgent Sale",
      "negotiable": "Negotiable",
      "villa_king_title": "Villa King Borey Peng Huoth (Boeng Snor)",
      "chbar_ampov": "Chbar Ampov",
      "shophouse_title_sale": "Shop House (Business House)",
      "sensokh": "Sen Sok",
      "land_near_airport": "Land lot near new airport",
      "ta_khmao": "Ta Khmao Town",
      "road_size": "🛣️ Next to state road {{size}}m",
      "water_electricity": "⚡ Has state water & electricity",
      "contact_info_btn": "Contact for info",
      "prev": "Previous",
      "next": "Next",
      "size_format": "{{value}} m",
      "properties_for_rent": "Properties for Rent",
      "available_units_count": "{{count}} available units",
      "per_month": "month",
      "book_now_btn": "Book Now",
      "modern_condo_studio": "Modern Condo (Studio Room)",
      "available_now": "Available Now",
      "fully_furnished": "Fully Furnished",
      "has_pool": "Has Swimming Pool",
      "news_hero_title": "Real Estate News & Insights",
      "news_hero_desc": "Stay updated with the latest news, market analysis, and useful tips regarding real estate investment in Cambodia.",
      "hot_news": "Hot News",
      "featured_news_title": "Economic Situation and Its Impact on the Construction Sector in 2026",
      "featured_news_desc": "Economic experts forecast that the real estate sector will experience a growth rate of 5.4% following the launch of the new airport...",
      "published_by": "Published by: {{author}}",
      "analyst_team": "Analysis Team",
      "featured_news_date": "June 02, 2026",
      "read_continue": "Read More",
      "latest_articles": "Latest Articles",
      "read_more": "Read Details",
      "newsletter_title": "Subscribe to Our Newsletter",
      "newsletter_desc": "We will send market updates and great investment opportunities to your email every week.",
      "email_placeholder": "Your email address...",
      "subscribe_btn": "Subscribe",
      "cat_market": "Market",
      "cat_knowledge": "Knowledge",
      "cat_legal": "Legal",
      "news_1_title": "Land Price Updates in Phnom Penh Suburbs for the First Half of 2026",
      "news_1_date": "June 02, 2026",
      "news_1_desc": "Land prices along Ring Road 3 are experiencing strong momentum...",
      "news_2_title": "5 Essential Tips Before Deciding to Buy Your First Condo",
      "news_2_date": "June 01, 2026",
      "news_2_desc": "Buying a condo is not just about the price, you also need to look at...",
      "news_3_title": "New Land Law: What Property Owners Need to Know",
      "news_3_date": "May 30, 2026",
      "news_3_desc": "Adjustments to the new procedures for transferring property ownership rights...",

      "contact_title": "Contact Us",
      "contact_subtitle": "We are always ready to answer your questions and meet your needs.",
      "contact_details": "Contact Details",
      "address_label": "Address",
      "address_value": "Street 101, Sangkat Boeung Keng Kang 1, Phnom Penh",
      "phone_label": "Phone Number",
      "follow_us": "Follow Us on Social Media",
      "send_message_title": "Send Us a Message",
      "full_name_label": "Full Name",
      "full_name_placeholder": "Enter your name...",
      "subject_label": "Subject",
      "subject_placeholder": "Inquiry about property for sale or rent...",
      "message_label": "Your Message",
      "message_placeholder": "Write your message here...",
      "send_button": "Send Message Now",
      "signup_hero_title_1": "Find Your Dream Home",
      "signup_hero_title_2": "With Us!",
      "signup_hero_desc_1": "Sign up to receive the latest real estate updates",
      "signup_hero_desc_2": "and exclusive offers before anyone else.",
      "signup_card_title": "Create New Account",
      "username_label": "Username",
      "username_placeholder": "Enter your username",
      "email_label": "Email",
      "password_placeholder": "Enter your password",
      "confirm_password_label": "Confirm Password",
      "confirm_password_placeholder": "Re-enter your password",
      "signup_btn": "Sign Up Now",
      "already_have_account": "Already have an account?",
      "login_link": "Login",
      "login_welcome_title": "Welcome to",
      "login_platform_name": "No. 1 Real Estate Platform",
      "login_welcome_desc_1": "Manage your buying, selling, and renting",
      "login_welcome_desc_2": "with ease and maximum security.",
      "login_title": "Login",
      "username_or_email_label": "Username or Email",
      "username_or_email_placeholder": "Enter username or email",
      "password_label": "Password",
      "password_placeholder": "Enter password",
      "forgot_password_link": "Forgot password?",
      "login_btn": "Login Now",
      "no_account_text": "Don't have an account yet?",
      "signup_link": "Sign Up Now",
    }
  },
  kh: {
    translation: {
      // Header
      "home": "ទំព័រដើម",
      "sale": "លក់",
      "rent": "ជួល",
      "news": "ព័ត៌មាន",
      "contact": "ទាក់ទងយើង",
      "signup": "ចុះឈ្មោះ",
      "login": "ចូលប្រើ",
      // Login & SignUp Page
      "username": "ឈ្មោះអ្នកប្រើប្រាស់",
      "password": "លេខសម្ងាត់",
      "email": "អ៊ីមែល",
      "confirm_password": "បញ្ជាក់លេខសម្ងាត់",
      "create_account": "បង្កើតគណនីថ្មី",
      "login_now": "ចូលប្រើប្រាស់ឥឡូវនេះ",
      "forgot_password": "ភ្លេចលេខសម្ងាត់?",
      "have_account": "មានគណនីរួចហើយមែនទេ?",
      "no_account": "មិនទាន់មានគណនីមែនទេ?",
      "welcome_title": "ស្វែងរកផ្ទះក្នុងក្តីសុបិន",
      "hero_title": "ស្វែងរកផ្ទះក្នុងក្តីសុបិនរបស់អ្នក",
      "hero_subtitle": "យើងផ្តល់ជូននូវសេវាកម្មទិញ លក់ និងជួលអចលនទ្រព្យដែលល្អបំផុតក្នុងប្រទេសកម្ពុជា",
      "search_placeholder": "ស្វែងរកទីតាំង ឬប្រភេទផ្ទះ...",
      "all_types": "គ្រប់ប្រភេទ",
      "search_btn": "ស្វែងរក",
      "our_services": "សេវាកម្មចម្បងរបស់យើង",
      "featured_projects": "គម្រោងថ្មីៗបំផុត",
      "curated_for_you": "ជ្រើសរើសដោយយកចិត្តទុកដាក់សម្រាប់អ្នក",
      "view_all": "មើលទាំងអស់",
      "special_offer": "ការផ្តល់ជូនពិសេស",
      "new_listing": "គម្រោងថ្មី",
      "hot_deal": "តម្លៃពិសេស",
      "villa_title": "វីឡាភ្លោះទំនើប តំបន់ជ្រោយចង្វារ",
      "shophouse_title": "ផ្ទះអាជីវកម្ម ជិតផ្សារទំនើប",
      "condo_title": "ខុនដូទំនើប កណ្តាលក្រុង",
      "phnom_penh": "រាជធានីភ្នំពេញ",
      "bed_count": "{{count}} បន្ទប់គេង",
      "bath_count": "{{count}} បន្ទប់ទឹក",
      "cta_title": "ចង់ដាក់លក់ ឬជួលអចលនទ្រព្យរបស់អ្នកមែនទេ?",
      "cta_subtitle": "ភ្នាក់ងារជំនាញរបស់យើងនឹងជួយអ្នកឱ្យទទួលបានតម្លៃខ្ពស់ និងលឿនបំផុត។",
      "consult_now": "ប្រឹក្សាយោបល់ឥឡូវនេះ",
      "default_service_desc": "ស្វែងរកជម្រើសល្អៗជាច្រើនកន្លែង",
      "footer_about": "យើងគឺជាភ្នាក់ងារអចលនទ្រព្យឈានមុខគេក្នុងប្រទេសកម្ពុជា ដែលផ្តល់ជូននូវសេវាកម្មទិញ លក់ និងជួល ប្រកបដោយទំនុកចិត្ត និងតម្លាភាពខ្ពស់បំផុតសម្រាប់អតិថិជន។",
      "quick_links": "តំណភ្ជាប់រហ័ស",
      "our_services_footer": "សេវាកម្មរបស់យើង",
      "service_1": "វាយតម្លៃអចលនទ្រព្យ",
      "service_2": "ប្រឹក្សាយោបល់ផ្នែកវិនិយោគ",
      "service_3": "សេវាកម្មផ្ទេរសិទ្ធិកាន់កាប់",
      "service_4": "គ្រប់គ្រងការជួលផ្ទះ/ខុនដូ",
      "contact_us_footer": "ទំនាក់ទំនង",
      "address": "បឹងកេងកង ១, រាជធានីភ្នំពេញ",
      "copyright": "© 2026 គ្រប់គ្រងដោយលោក Meng Hor រក្សាសិទ្ធិគ្រប់យ៉ាង",
      "properties_for_sale": "អចលនទ្រព្យសម្រាប់លក់",
      "showing_results": "បង្ហាញលទ្ធផល: {{count}} ទីតាំង",
      "all_locations": "គ្រប់ទីតាំង",
      "kandal": "កណ្តាល",
      "siem_reap": "សៀមរាប",
      "property_type": "ប្រភេទអចលនទ្រព្យ",
      "villa": "វីឡា",
      "flat": "ផ្ទះល្វែង",
      "land_lot": "ដីឡូតិ៍",
      "price_range": "កម្រិតតម្លៃ",
      "under_50k": "ក្រោម $50,000",
      "50k_100k": "$50,000 - $100,000",
      "over_100k": "លើសពី $100,000",
      "hard_title": "ប្លង់រឹង",
      "urgent_sale": "លក់បន្ទាន់",
      "negotiable": "អាចចរចាបាន",
      "villa_king_title": "វីឡាឃីង បុរីប៉េងហួត (បឹងស្នោរ)",
      "chbar_ampov": "ច្បារអំពៅ",
      "shophouse_title_sale": "ផ្ទះអាជីវកម្ម (Shop House)",
      "sensokh": "សែនសុខ",
      "land_near_airport": "ដីឡូតិ៍ក្បែរព្រលានយន្តហោះថ្មី",
      "ta_khmao": "ក្រុងតាខ្មៅ",
      "road_size": "🛣️ ជាប់ផ្លូវរដ្ឋ {{size}}ម",
      "water_electricity": "⚡ មានទឹកភ្លើងរដ្ឋ",
      "contact_info_btn": "ទាក់ទងសួរព័ត៌មាន",
      "prev": "ថយក្រោយ",
      "next": "បន្ទាប់",
      "size_format": "{{value}} ម៉ែត្រ",
      "properties_for_rent": "អចលនទ្រព្យសម្រាប់ជួល",
      "available_units_count": "មានទីតាំងទំនេរចំនួន {{count}} កន្លែង",
      "per_month": "ខែ",
      "book_now_btn": "កក់ទុកមុន",
      "modern_condo_studio": "ខុនដូទំនើប (Studio Room)",
      "available_now": "ទំនេរឥឡូវនេះ",
      "fully_furnished": "មានគ្រឿងសង្ហារិមពេញ",
      "has_pool": "មានអាងហែលទឹក",
      "news_hero_title": "ព័ត៌មាន និងចំណេះដឹងអចលនទ្រព្យ",
      "news_hero_desc": "តាមដានរាល់ព័ត៌មានថ្មីៗ ការវិភាគទីផ្សារ និងគន្លឹះល្អៗទាក់ទងនឹងការវិនិយោគអចលនទ្រព្យក្នុងប្រទេសកម្ពុជា។",
      "hot_news": "ព័ត៌មានក្តៅៗ",
      "featured_news_title": "ស្ថានភាពសេដ្ឋកិច្ច និងឥទ្ធិពលលើវិស័យសំណង់ឆ្នាំ ២០២៦",
      "featured_news_desc": "អ្នកជំនាញសេដ្ឋកិច្ចបានព្យាករណ៍ថា វិស័យអចលនទ្រព្យនឹងមានការកើនឡើងក្នុងកម្រិត ៥.៤% បន្ទាប់ពីការបើកដំណើរការព្រលានយន្តហោះថ្មី...",
      "published_by": "ចេញផ្សាយដោយ៖ {{author}}",
      "analyst_team": "ក្រុមការងារផ្នែកវិភាគ",
      "featured_news_date": "ថ្ងៃទី ០២ មិថុនា ២០២៦",
      "read_continue": "អានបន្ត",
      "latest_articles": "អត្ថបទថ្មីៗ",
      "read_more": "អានលម្អិត",
      "newsletter_title": "ចុះឈ្មោះដើម្បីទទួលបានព័ត៌មានថ្មីៗ",
      "newsletter_desc": "យើងនឹងផ្ញើព័ត៌មានទីផ្សារ និងឱកាសវិនិយោគល្អៗជូនបងតាមរយៈ Email រៀងរាល់សប្តាហ៍។",
      "email_placeholder": "អ៊ីមែលរបស់អ្នក...",
      "subscribe_btn": "ចុះឈ្មោះ",
      "cat_market": "ទីផ្សារ",
      "cat_knowledge": "ចំណេះដឹង",
      "cat_legal": "ច្បាប់",
      "news_1_title": "បច្ចុប្បន្នភាពតម្លៃដីធ្លីនៅតំបន់ជាយក្រុងភ្នំពេញ សម្រាប់ឆមាសទី១ ឆ្នាំ២០២៦",
      "news_1_date": "០២ មិថុនា ២០២៦",
      "news_1_desc": "តម្លៃដីធ្លីនៅតាមបណ្តោយផ្លូវក្រវាត់ក្រុងទី៣ កំពុងមានសន្ទុះខ្លាំង...",
      "news_2_title": "គន្លឹះសំខាន់ៗ ៥ យ៉ាងមុននឹងសម្រេចចិត្តទិញខុនដូដំបូងរបស់អ្នក",
      "news_2_date": "០១ មិថុនា ២០២៦",
      "news_2_desc": "ការទិញខុនដូមិនមែនត្រឹមតែមើលលើតម្លៃនោះទេ ប៉ុន្តែត្រូវមើលលើ...",
      "news_3_title": "ច្បាប់ភូមិបាលថ្មី៖ អ្វីខ្លះដែលម្ចាស់អចលនទ្រព្យត្រូវដឹង?",
      "news_3_date": "៣០ ឧសភា ២០២៦",
      "news_3_desc": "ការកែសម្រួលនីតិវិធីនៃការផ្ទេរសិទ្ធិកាន់កាប់អចលនទ្រព្យថ្មី...",

      "contact_title": "ទំនាក់ទំនងយើងខ្ញុំ",
      "contact_subtitle": "យើងខ្ញុំត្រៀមខ្លួនជានិច្ចដើម្បីឆ្លើយតបរាល់ចម្ងល់ និងការចង់បានរបស់បង",
      "contact_details": "ព័ត៌មានលម្អិត",
      "address_label": "អាសយដ្ឋាន",
      "address_value": "ផ្លូវលេខ ១០១, សង្កាត់បឹងកេងកង ១, រាជធានីភ្នំពេញ",
      "phone_label": "លេខទូរស័ព្ទ",
      "email_label": "អ៊ីមែល",
      "follow_us": "តាមដានយើងខ្ញុំលើបណ្តាញសង្គម",
      "send_message_title": "ផ្ញើសារមកកាន់យើង",
      "full_name_label": "ឈ្មោះពេញ",
      "full_name_placeholder": "បញ្ចូលឈ្មោះបង...",
      "subject_label": "ប្រធានបទ",
      "subject_placeholder": "ចង់សួរអំពីផ្ទះលក់ ឬជួល...",
      "message_label": "សាររបស់អ្នក",
      "message_placeholder": "សរសេរសារនៅទីនេះ...",
      "send_button": "ផ្ញើសារឥឡូវនេះ",
      "signup_hero_title_1": "ស្វែងរកផ្ទះក្នុងក្តីសុបិន",
      "signup_hero_title_2": "ជាមួយយើង!",
      "signup_hero_desc_1": "ចុះឈ្មោះដើម្បីទទួលបានព័ត៌មានអចលនទ្រព្យថ្មីៗ",
      "signup_hero_desc_2": "និងការផ្ដើជូនពិសេសមុនគេ។",
      "signup_card_title": "បង្កើតគណនីថ្មី",
      "username_label": "ឈ្មោះអ្នកប្រើប្រាស់",
      "username_placeholder": "បញ្ចូលឈ្មោះរបស់អ្នក",
      "email_label": "អ៊ីមែល",
      "password_label": "លេខសម្ងាត់",
      "password_placeholder": "បញ្ចូលលេខសម្ងាត់",
      "confirm_password_label": "បញ្ជាក់លេខសម្ងាត់",
      "confirm_password_placeholder": "វាយលេខសម្ងាត់ម្ដងទៀត",
      "signup_btn": "ចុះឈ្មោះឥឡូវនេះ",
      "already_have_account": "មានគណនីរួចហើយមែនទេ?",
      "login_link": "ចូលប្រើប្រាស់",
      "login_welcome_title": "ស្វាគមន៍មកកាន់",
      "login_platform_name": "វេទិកាអចលនទ្រព្យលេខ១",
      "login_welcome_desc_1": "គ្រប់គ្រងការទិញ លក់ និងជួលផ្ទះរបស់អ្នក",
      "login_welcome_desc_2": "ដោយភាពងាយស្រួល និងសុវត្ថិភាពបំផុត។",
      "login_title": "ចូលប្រើប្រាស់",
      "username_or_email_label": "ឈ្មោះអ្នកប្រើប្រាស់ ឬ អ៊ីមែល",
      "username_or_email_placeholder": "បញ្ចូលឈ្មោះ ឬអ៊ីមែល",
      "password_label": "លេខសម្ងាត់",
      "password_placeholder": "បញ្ចូលលេខសម្ងាត់",
      "forgot_password_link": "ភ្លេចលេខសម្ងាត់?",
      "login_btn": "ចូលប្រើប្រាស់ឥឡូវនេះ",
      "no_account_text": "មិនទាន់មានគណនីមែនទេ?",
      "signup_link": "ចុះឈ្មោះថ្មី",


    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en', // បើរកភាសាមិនឃើញ វានឹងប្រើអង់គ្លេស
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;