import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      // Header
      "home": "Home",
      "sale": "Sale",
      "rent": "Rent",
      "news": "News",
      "contact": "Contact Us",
      "signup": "Sign Up",
      "login": "Login",
      // Login & SignUp Page
      "username": "Username",
      "password": "Password",
      "email": "Email",
      "confirm_password": "Confirm Password",
      "create_account": "Create New Account",
      "login_now": "Login Now",
      "forgot_password": "Forgot Password?",
      "have_account": "Already have an account?",
      "no_account": "Don't have an account?",
      "welcome_title": "Find Your Dream Home",
      "hero_title": "Find Your Dream Home",
      "hero_subtitle": "We provide the best real estate buy, sell, and rent services in Cambodia",
      "search_placeholder": "Search location or property type...",
      "all_types": "All Types",
      "search_btn": "Search",
      "our_services": "Our Main Services",
      "featured_projects": "Latest Projects",
      "curated_for_you": "Carefully selected for you",
      "view_all": "View All",
      "special_offer": "Special Offer",
      "new_listing": "New Listing",
      "hot_deal": "Hot Deal",
      "villa_title": "Modern Twin Villa Chroy Changvar",
      "shophouse_title": "Shophouse near Mall",
      "condo_title": "Modern Condo City Center",
      "phnom_penh": "Phnom Penh",
      "bed_count": "{{count}} Bedrooms",
      "bath_count": "{{count}} Bathrooms",
      "cta_title": "Want to sell or rent your property?",
      "cta_subtitle": "Our expert agents will help you get the best price quickly.",
      "consult_now": "Consult Now",
      "default_service_desc": "Explore many great options available.",
      "footer_about": "We are a leading real estate agency in Cambodia, providing buying, selling, and renting services with the highest trust and transparency for our customers.",
      "quick_links": "Quick Links",
      "our_services_footer": "Our Services",
      "service_1": "Property Valuation",
      "service_2": "Investment Consulting",
      "service_3": "Ownership Transfer Service",
      "service_4": "Rental Property Management",
      "contact_us_footer": "Contact Us",
      "address": "Boeung Keng Kang 1, Phnom Penh",
      "copyright": "© 2026 Managed by Mr. Meng Hor. All Rights Reserved.",
      "properties_for_sale": "Properties For Sale",
      "showing_results": "Showing results: {{count}} locations",
      "all_locations": "All Locations",
      "kandal": "Kandal",
      "siem_reap": "Siem Reap",
      "property_type": "Property Type",
      "villa": "Villa",
      "flat": "FlatHouse/Apartment",
      "land_lot": "Land Lot",
      "price_range": "Price Range",
      "under_50k": "Under $50,000",
      "50k_100k": "$50,000 - $100,000",
      "over_100k": "Over $100,000",
      "hard_title": "Hard Title",
      "urgent_sale": "Urgent Sale",
      "negotiable": "Negotiable",
      "villa_king_title": "Villa King Borey Peng Huoth (Boeng Snor)",
      "chbar_ampov": "Chbar Ampov",
      "shophouse_title_sale": "Shop House (Business House)",
      "sensokh": "Sen Sok",
      "land_near_airport": "Land lot near new airport",
      "ta_khmao": "Ta Khmao Town",
      "road_size": "🛣️ Next to state road {{size}}m",
      "water_electricity": "⚡ Has state water & electricity",
      "contact_info_btn": "Contact for info",
      "prev": "Previous",
      "next": "Next",
      "size_format": "{{value}} m",
      "properties_for_rent": "Properties for Rent",
      "available_units_count": "{{count}} available units",
      "per_month": "month",
      "book_now_btn": "Book Now",
      "modern_condo_studio": "Modern Condo (Studio Room)",
      "available_now": "Available Now",
      "fully_furnished": "Fully Furnished",
      "has_pool": "Has Swimming Pool",

    }
  },
  kh: {
    translation: {
      // Header
      "home": "ទំព័រដើម",
      "sale": "លក់",
      "rent": "ជួល",
      "news": "ព័ត៌មាន",
      "contact": "ទាក់ទងយើង",
      "signup": "ចុះឈ្មោះ",
      "login": "ចូលប្រើ",
      // Login & SignUp Page
      "username": "ឈ្មោះអ្នកប្រើប្រាស់",
      "password": "លេខសម្ងាត់",
      "email": "អ៊ីមែល",
      "confirm_password": "បញ្ជាក់លេខសម្ងាត់",
      "create_account": "បង្កើតគណនីថ្មី",
      "login_now": "ចូលប្រើប្រាស់ឥឡូវនេះ",
      "forgot_password": "ភ្លេចលេខសម្ងាត់?",
      "have_account": "មានគណនីរួចហើយមែនទេ?",
      "no_account": "មិនទាន់មានគណនីមែនទេ?",
      "welcome_title": "ស្វែងរកផ្ទះក្នុងក្តីសុបិន",
      "hero_title": "ស្វែងរកផ្ទះក្នុងក្តីសុបិនរបស់អ្នក",
      "hero_subtitle": "យើងផ្តល់ជូននូវសេវាកម្មទិញ លក់ និងជួលអចលនទ្រព្យដែលល្អបំផុតក្នុងប្រទេសកម្ពុជា",
      "search_placeholder": "ស្វែងរកទីតាំង ឬប្រភេទផ្ទះ...",
      "all_types": "គ្រប់ប្រភេទ",
      "search_btn": "ស្វែងរក",
      "our_services": "សេវាកម្មចម្បងរបស់យើង",
      "featured_projects": "គម្រោងថ្មីៗបំផុត",
      "curated_for_you": "ជ្រើសរើសដោយយកចិត្តទុកដាក់សម្រាប់អ្នក",
      "view_all": "មើលទាំងអស់",
      "special_offer": "ការផ្តល់ជូនពិសេស",
      "new_listing": "គម្រោងថ្មី",
      "hot_deal": "តម្លៃពិសេស",
      "villa_title": "វីឡាភ្លោះទំនើប តំបន់ជ្រោយចង្វារ",
      "shophouse_title": "ផ្ទះអាជីវកម្ម ជិតផ្សារទំនើប",
      "condo_title": "ខុនដូទំនើប កណ្តាលក្រុង",
      "phnom_penh": "រាជធានីភ្នំពេញ",
      "bed_count": "{{count}} បន្ទប់គេង",
      "bath_count": "{{count}} បន្ទប់ទឹក",
      "cta_title": "ចង់ដាក់លក់ ឬជួលអចលនទ្រព្យរបស់អ្នកមែនទេ?",
      "cta_subtitle": "ភ្នាក់ងារជំនាញរបស់យើងនឹងជួយអ្នកឱ្យទទួលបានតម្លៃខ្ពស់ និងលឿនបំផុត។",
      "consult_now": "ប្រឹក្សាយោបល់ឥឡូវនេះ",
      "default_service_desc": "ស្វែងរកជម្រើសល្អៗជាច្រើនកន្លែង",
      "footer_about": "យើងគឺជាភ្នាក់ងារអចលនទ្រព្យឈានមុខគេក្នុងប្រទេសកម្ពុជា ដែលផ្តល់ជូននូវសេវាកម្មទិញ លក់ និងជួល ប្រកបដោយទំនុកចិត្ត និងតម្លាភាពខ្ពស់បំផុតសម្រាប់អតិថិជន។",
      "quick_links": "តំណភ្ជាប់រហ័ស",
      "our_services_footer": "សេវាកម្មរបស់យើង",
      "service_1": "វាយតម្លៃអចលនទ្រព្យ",
      "service_2": "ប្រឹក្សាយោបល់ផ្នែកវិនិយោគ",
      "service_3": "សេវាកម្មផ្ទេរសិទ្ធិកាន់កាប់",
      "service_4": "គ្រប់គ្រងការជួលផ្ទះ/ខុនដូ",
      "contact_us_footer": "ទំនាក់ទំនង",
      "address": "បឹងកេងកង ១, រាជធានីភ្នំពេញ",
      "copyright": "© 2026 គ្រប់គ្រងដោយលោក Meng Hor រក្សាសិទ្ធិគ្រប់យ៉ាង",
      "properties_for_sale": "អចលនទ្រព្យសម្រាប់លក់",
      "showing_results": "បង្ហាញលទ្ធផល: {{count}} ទីតាំង",
      "all_locations": "គ្រប់ទីតាំង",
      "kandal": "កណ្តាល",
      "siem_reap": "សៀមរាប",
      "property_type": "ប្រភេទអចលនទ្រព្យ",
      "villa": "វីឡា",
      "flat": "ផ្ទះល្វែង",
      "land_lot": "ដីឡូតិ៍",
      "price_range": "កម្រិតតម្លៃ",
      "under_50k": "ក្រោម $50,000",
      "50k_100k": "$50,000 - $100,000",
      "over_100k": "លើសពី $100,000",
      "hard_title": "ប្លង់រឹង",
      "urgent_sale": "លក់បន្ទាន់",
      "negotiable": "អាចចរចាបាន",
      "villa_king_title": "វីឡាឃីង បុរីប៉េងហួត (បឹងស្នោរ)",
      "chbar_ampov": "ច្បារអំពៅ",
      "shophouse_title_sale": "ផ្ទះអាជីវកម្ម (Shop House)",
      "sensokh": "សែនសុខ",
      "land_near_airport": "ដីឡូតិ៍ក្បែរព្រលានយន្តហោះថ្មី",
      "ta_khmao": "ក្រុងតាខ្មៅ",
      "road_size": "🛣️ ជាប់ផ្លូវរដ្ឋ {{size}}ម",
      "water_electricity": "⚡ មានទឹកភ្លើងរដ្ឋ",
      "contact_info_btn": "ទាក់ទងសួរព័ត៌មាន",
      "prev": "ថយក្រោយ",
      "next": "បន្ទាប់",
      "size_format": "{{value}} ម៉ែត្រ",
      "properties_for_rent": "អចលនទ្រព្យសម្រាប់ជួល",
      "available_units_count": "មានទីតាំងទំនេរចំនួន {{count}} កន្លែង",
      "per_month": "ខែ",
      "book_now_btn": "កក់ទុកមុន",
      "modern_condo_studio": "ខុនដូទំនើប (Studio Room)",
      "available_now": "ទំនេរឥឡូវនេះ",
      "fully_furnished": "មានគ្រឿងសង្ហារិមពេញ",
      "has_pool": "មានអាងហែលទឹក",


    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en', // បើរកភាសាមិនឃើញ វានឹងប្រើអង់គ្លេស
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;